### ISSUE TITLE
[Epic] Upgrade upstream apps to new versions

### ISSUE THREAD

**Issue by Pavan-Gunda** [elastisys/compliantkubernetes-apps#1024]
**What Chart should be upgraded?**

- [x] upstream / certmanager #1221 
- [ ] upstream / falco #1405
- [x] upstream / falco-exporter #1016
- [ ] https://github.com/elastisys/compliantkubernetes-apps/issues/1362
- [ ] upstream / fluentd #1222
- [ ] upstream / fluentd-elasticsearch #1223
- [x] upstream / gatekeeper #1224
- [ ] upstream / ingress-nginx #1225 
- [x] upstream / kured #1226 
- [x] upstream / metrics-server #1227
- [x] upstream / starbord-operator #1228 
- [ ] upstream / prometheus-elasticsearch-exporter #1229 
- [ ] upstream / prometheus-blackbox-exporter #1230 
- [ ] upstream / dex #1406
- [ ] upstream / thanos #1023
- [x] upstream / kube-prometheus-stack #1020
- [ ] upstream / grafana #1407 
- [ ] upstream / harbor #1404
- [ ] upstream / node-local-dns  #1408 
- [ ] upstream / velero #1480 

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [ ] Other: *Write the reason here*

**Acceptance criteria**

- I checked the migration of the new Chart:
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

**Comment by raviranjanelastisys** [comment]
This Epic is closed in favor of new structure suggested - https://github.com/elastisys/ck8s-ops/issues/3749#issuecomment-1486430046
