### ISSUE TITLE
[Epics] Remove use of PSPs

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#1218]
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/1147
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/1324
- [x] https://github.com/elastisys/compliantkubernetes-kubespray/issues/74
- [x] https://github.com/elastisys/ck8s-ops/issues/3446
- [x] https://github.com/elastisys/ck8s-ops/issues/3448
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/1447
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/1446
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/1448
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/1449
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/1450
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/1451
- [x] https://github.com/elastisys/ck8s-jaeger/issues/45
- [x] https://github.com/elastisys/ck8s-argocd/issues/66
- [x] https://github.com/elastisys/compliantkubernetes-postgresql/issues/182
- [x] https://github.com/elastisys/compliantkubernetes-redis/issues/98
- [x] https://github.com/elastisys/compliantkubernetes-rabbitmq/issues/97
- [x] https://github.com/elastisys/ck8s-ops/issues/3748
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/1530
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/1541
