### ISSUE TITLE
[Epic] Q2-Analyzed/Upgrade upstream apps to new versions

### ISSUE THREAD

**Issue by raviranjanelastisys** [elastisys/compliantkubernetes-apps#1490]
**Q2-Charts to be upgraded**

- [ ] upstream / fluentd #1222
- [ ] upstream / fluentd-elasticsearch #1223
- [ ] upstream / metrics-server #1487 
- [ ] upstream / prometheus-elasticsearch-exporter #1229 
- [ ] upstream / dex #1406
- [ ] upstream / harbor #1404
- [ ] upstream / node-local-dns  #1408 
- [ ] upstream / velero #1480 
- [ ] upstream / opensearch #1362

**Q2-Charts Analyzed - To be upgraded in Q3**

- [x] upstream / gatekeeper #1224
- [ ] upstream / ingress-nginx #1225 
- [ ] upstream / kured #1489 
- [x] upstream / starbord-operator #1228 
- [ ] upstream / prometheus-blackbox-exporter #1230 
- [ ] upstream / thanos #1023
- [ ] upstream / kube-prometheus-stack #1486 
- [ ] upstream / grafana #1407 
- [x] upstream / certmanager #1221 
- [ ] upstream / falco #1405
- [ ] upstream / falco-exporter #1488

**Comment by raviranjanelastisys** [comment]
@crssnd closed ? Still many charts to be upgraded in Q2 as mentioned above.

**Comment by crssnd** [comment]
yes, we already have the epics for the Q upgrades, so this was closed as it is a duplicate

**Comment by raviranjanelastisys** [comment]
> yes, we already have the epics for the Q upgrades, so this was closed as it is a duplicate

But we closed the older one as in favor of making it seperate -  https://github.com/elastisys/compliantkubernetes-apps/issues/1024
