### ISSUE TITLE
[Epic] Define platform prometheus metrics

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#1818]
We want to define what metrics we have and what we use and how we can drop some of the metrics to reduce (read optimize) the footprint for the monitoring stack.

- [ ] https://github.com/elastisys/compliantkubernetes-apps/issues/1736
- [ ] [Placeholder] Create investigation task on how to best collect available metrics
- [ ] [Placeholder] Look at have heavy series generating metrics and drop them
