### ISSUE TITLE
Starboard

### ISSUE THREAD

**Issue by robinAwallace** [elastisys/compliantkubernetes-apps#585]
**Describe the bug**

- [x] Error getting resource - causing panic? #573
- [x] Error downloading vulnerability report DB - API rate limit exceeded #572
- [x] Unable to initialize a docker scanner #574
- [x] Observed a panic: "invalid memory address or nil pointer dereference" #579
- [x] Unable to scan images from private container registries (harbor) #580
- [x] Crashed due to too long resource names(?) #583
- [x] Make it possible to disable starboard #492
