### ISSUE TITLE
User-facing API

### ISSUE THREAD

**Issue by robinAwallace** [elastisys/compliantkubernetes-apps#592]
**Epic parts**

- [ ] Prepare a list of user facing API:s #589
- [ ] https://github.com/elastisys/ck8s-ops/issues/2951
- [x] Create an issue template to check for apps upgrades [#491](https://github.com/elastisys/ck8s-ops/issues/491)
- [x] Update release process document (inform customers) [#492](https://github.com/elastisys/ck8s-ops/issues/492)
- [x] Create a user facing changelog #590

**Comment by crssnd** [comment]
closing the epic
