### ISSUE TITLE
Prepare for K8s v1.22

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#669]
A major change in Kubernetes version 1.22 is that [several alpha and beta API versions are getting removed](https://kubernetes.io/blog/2021/08/04/kubernetes-1-22-release-announcement/#removal-of-several-deprecated-beta-apis). 
Several components needs to be upgraded to prepare for this version.

- [x] charts / blackbox / blackbox-exporter: #660 
- [x] charts / kubeapi-metrics: #668 
- [x] upstream / cert-manager: #661 
- [x] upstream / dex: #662 
- [x] upstream / gatekeeper: #663 
- [x] upstream / kube-prometheus-stack: #664 
- [x] upstream / metrics-server: #665 
- [x] upstream / velero: #666 
- [x] upstream / prometheus-elasticsearch-exporter: #826
---
- [x] upstream / ingress-nginx - _v0.x -> v1.x, Requires that all apps already use GA ingress API version_ #805 

## AMS
- [x] redis operator to v1.1.1 elastisys/compliantkubernetes-redis#23
- [x] rabbitmq operator to v1.11.1 elastisys/compliantkubernetes-rabbitmq#12
