### ISSUE TITLE
Investigate alternative CD solutions

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#974]
**What should be investigated.**

We are somewhat unconvinced about using Tekton for automatic security patching and updates of compliantkubernetes apps. Let's dig more before taking a decision.

Investigate each $candidate:
- [x] [TektonCD](https://github.com/elastisys/compliantkubernetes-apps/issues/1003)
- [x] [ArgoCD](https://github.com/elastisys/compliantkubernetes-apps/issues/1001)
- [x] [Flux2](https://github.com/elastisys/compliantkubernetes-apps/issues/1002)
- [x] [simple CronJob](https://github.com/elastisys/compliantkubernetes-apps/issues/1004)

**Comment by raviranjanelastisys** [comment]
Based on the detailed investigations of all the above 4 alternatives - It's results are compiled in one Doc - https://docs.google.com/spreadsheets/d/1AGIEX2L_ZQw71y4qz-_g-ZIb48jpAurSWjl_zTgfgAk/edit#gid=0

**Comment by raviranjanelastisys** [comment]
Based on the architecture meeting discussion happened on 25-08-2022 - https://docs.google.com/presentation/d/18cY5ynwY33q-D5GUoo5rM8mRsOQdehihUw1ioTSTCQs/edit#slide=id.g137fbaf61ac_0_0 , we decided to use the `tekton` for our internal automations apps upgrade CD solutions !!
