### ISSUE TITLE
Fluentd Epic

### ISSUE THREAD

**Issue by robinAwallace** [elastisys/compliantkubernetes-apps#986]
Epic to keep track of all fluentd issues. 

Issues concerning fluentd:
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/847
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/810
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/809
- [ ] https://github.com/elastisys/compliantkubernetes-apps/issues/612
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/570
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/569
- [ ] https://github.com/elastisys/compliantkubernetes-apps/issues/576
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/544
- [ ] https://github.com/elastisys/compliantkubernetes-apps/issues/368
- [ ] https://github.com/elastisys/compliantkubernetes-apps/issues/987
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/988
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/989
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/990
- [x] https://github.com/elastisys/compliantkubernetes-apps/issues/991
- [ ] https://github.com/elastisys/compliantkubernetes-apps/issues/992

**Comment by crssnd** [comment]
we will keep the issues, for now, but close the epic
