### ISSUE TITLE
[1]Look through all current versions of apps and suggest upgrades

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#998]
We should look through the versions we are using now of all apps and figure out if we should upgrade to the latest version or if it can wait.

Create issues for the ones that we should upgrade and document the process/findings.

Things left over from last time https://github.com/elastisys/compliantkubernetes-apps/issues/673

_Copied from comment below_

- [ ] upstream / certmanager #1015
- [ ] upstream / falco #1017
- [ ] upstream / falco-exporter #1016
- [ ] upstream / opensearch #1022
- [ ] upstream / opensearch-dashboards #1021
- [ ] upstream / thanos #1023
- [ ] upstream / kube-prometheus-stack #1020
- [ ] upstream / grafana #1018
- [ ] upstream / harbor #1019

**Comment by Pavan-Gunda** [comment]
https://docs.google.com/document/d/1xQPZD179dVlh7XAM2TpZSTshiGcDNQoJ65Yhx_b4lx0/edit
